# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-14 11:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('college', models.CharField(choices=[('PCCOE', 'Pimpri Chinchwad College of Engineering,Pune'), ('DYAK', 'D.Y. Patil Akurdi'), ('DYAM', 'D.Y. Patil Ambi'), ('DYPI', 'D.Y. Patil Pimpri'), ('JSPM', 'J.S.P.M. Tatawade'), ('Other', 'Other')], max_length=20)),
                ('year', models.CharField(choices=[('FE', 'FE'), ('SE', 'SE'), ('TE', 'TE'), ('BE', 'BE')], max_length=20)),
                ('course', models.CharField(choices=[('C', 'C'), ('C++', 'C++'), ('Python', 'Python'), ('Django', 'Django')], max_length=20)),
                ('interest', models.CharField(max_length=50)),
            ],
        ),
    ]
