# Generated by Django 2.2.6 on 2019-11-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackbatch',
            name='feedback_title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
