# Generated by Django 2.2.7 on 2019-11-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studycourse',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
