# Generated by Django 2.2 on 2019-11-09 05:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('course_name', models.CharField(max_length=30)),
                ('material_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='syllabus',
            field=models.FileField(upload_to=''),
        ),
    ]
