# Generated by Django 2.2.7 on 2019-11-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_no', models.CharField(max_length=10)),
                ('company_name', models.CharField(max_length=70)),
                ('designation', models.CharField(max_length=70)),
                ('message', models.TextField()),
            ],
        ),
    ]
