# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-15 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admission',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
