# Generated by Django 2.2.7 on 2019-11-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_studycourse_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='studycourse',
            name='course_slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
