# Generated by Django 2.2.7 on 2019-11-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20191116_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='college',
            field=models.ForeignKey(on_delete=models.SET('OTHER'), to='home.College'),
        ),
    ]
