# Generated by Django 2.2.6 on 2019-11-22 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_feedbackbatch_feedback_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbackbatch',
            old_name='datetime',
            new_name='date_time',
        ),
    ]
