# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-15 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_student_admission'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fees_paid',
            field=models.IntegerField(default=0),
        ),
    ]
