# Generated by Django 2.2.7 on 2019-11-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_studycourse_course_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
