# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-15 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_student_fees_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=15)),
                ('course_icon', models.FileField(upload_to=b'')),
                ('fees', models.IntegerField()),
                ('outcomes', models.CharField(max_length=300)),
                ('requirements', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
    ]
