# Generated by Django 2.2.4 on 2019-11-13 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_course_course_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='course_batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=30)),
                ('batch_id', models.CharField(max_length=10, unique=True)),
                ('batch_duration', models.CharField(max_length=10)),
                ('batch_teacher', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='feedback_question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.TextField()),
                ('question_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='feedback_response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField(max_length=10)),
                ('batch_id', models.CharField(max_length=10)),
                ('response', models.TextField()),
                ('studemt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Student')),
            ],
        ),
    ]
