# Generated by Django 2.2.6 on 2019-11-15 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_course_course_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True)),
                ('batch_name', models.CharField(max_length=30)),
                ('fees', models.IntegerField(max_length=10)),
                ('feedback_enable', models.BooleanField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Course', to_field='course_name')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.TextField()),
                ('question_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('batch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.CourseBatch')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.FeedbackQuestion')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Student')),
            ],
        ),
    ]
