# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-15 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('Beginer', 'Beginer'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginer', max_length=10),
            preserve_default=False,
        ),
    ]
