# Generated by Django 2.2.6 on 2019-11-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_coursebatch_feedbackquestion_feedbackresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursebatch',
            name='fees',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='feedbackquestion',
            name='question_type',
            field=models.CharField(choices=[('comment', 'comment'), ('rating', 'rating')], max_length=10),
        ),
    ]
