# Generated by Django 2.2.4 on 2019-11-16 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_course_batch_feedback_question_feedback_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True)),
                ('batch_name', models.CharField(max_length=30)),
                ('fees', models.IntegerField(max_length=10)),
                ('feedback_enable', models.BooleanField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Course', to_field='course_name')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('batch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.CourseBatch')),
            ],
        ),
        migrations.DeleteModel(
            name='course_batch',
        ),
        migrations.RenameModel(
            old_name='feedback_question',
            new_name='FeedbackQuestion',
        ),
        migrations.DeleteModel(
            name='feedback_response',
        ),
        migrations.AddField(
            model_name='feedbackresponse',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.FeedbackQuestion'),
        ),
        migrations.AddField(
            model_name='feedbackresponse',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Student'),
        ),
    ]
