# Generated by Django 2.2.6 on 2019-11-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20191122_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackbatch',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='feedbackbatch',
            name='start_date',
            field=models.DateField(),
        ),
    ]
