# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-15 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20171115_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='course',
            name='fees',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission',
            field=models.BooleanField(default=False),
        ),
    ]
