# Generated by Django 2.2.4 on 2019-11-22 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20191116_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbackresponse',
            old_name='batch_id',
            new_name='feedback_batch_id',
        ),
        migrations.AlterField(
            model_name='coursebatch',
            name='fees',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='feedbackquestion',
            name='question_type',
            field=models.CharField(choices=[('comment', 'comment'), ('rating', 'rating')], max_length=10),
        ),
        migrations.CreateModel(
            name='FeedbackBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('batch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.CourseBatch')),
            ],
        ),
    ]
