# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-16 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20171115_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='outcomes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='requirements',
            field=models.TextField(),
        ),
    ]
