# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-17 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20171116_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='syllabus_link',
            field=models.CharField(default='https://drive.google.com/open?id=0B7SqFrXEtBojV1kwdkRRTDEyTl91NnJEVGw0X2g1QkVSUkhR', max_length=150),
            preserve_default=False,
        ),
    ]
