# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-17 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_course_syllabus_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='syllabus_link',
        ),
        migrations.AddField(
            model_name='course',
            name='syllabus',
            field=models.FileField(null=True, upload_to=b''),
        ),
    ]
